name: ZiYuUiCI

on:
  push:
    branch: [master]
  pull_request:
    branch: [master]

jobs:
  Lint:
    # Lint任务
  UnitTest:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - uses: pnpm/action-setup@v2.1.0
      with:
        version: 7.2.1
    - name: Install modules
      run: pnpm install
    - name: Run Test
      run: pnpm run test:git
  UnitTest:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - uses: pnpm/action-setup@v2.1.0
      with:
        version: 7.2.1
    - name: Install modules
      run: pnpm install
    - name: Run Lint
      run: pnpm run lint:all:eslint
