name: Publish ZiYu-vite-ui To Npm

on:
  push:
    branches: [publish-ziyu-vite-ui]

env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store
jobs:
  publish:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    name: 'publish npm'

    steps:
      - name: checkout code repository
      - uses: actions/checkout@master
      - name: setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: install pnpm
        run: npm i pnpm@latest -g
      - name: Setup npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_VITE_UI_AUTH_TOKEN }}" > .npmrc
      - name: setup pnpm config
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER
      - name: install dependencies
        run: pnpm install
      - name: Build
        run: pnpm run build:UI
      - name: create and publish versions
        uses: changesets/action@v1
        with:
          version: pnpm ci:version
          commit: 'chore: update versions'
          title: 'chore: update versions'
          publish: pnpm ci:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: 'Publish to the npm registry'
      #   uses: primer/publish@3.0.0
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     NPM_AUTH_TOKEN: ${{ secrets.NPM_VITE_UI_AUTH_TOKEN }} # 跟前面步骤中的 NPM_VITE_UI_AUTH_TOKEN 保持一致
      #   with:
      #     default_branch: 'publish-ziyu-vite-ui'
      #     npm-args: '--filter ziyu-vite-ui --unsafe-perm --allow-same-version'
